import type { FeedPost, Restaurant, Review } from "./types";

export const CITIES = [
  { id: "dallas" as const, name: "Dallas", state: "TX", live: true },
  { id: "kansas-city" as const, name: "Kansas City", state: "MO/KS", live: false },
  { id: "tulsa" as const, name: "Tulsa", state: "OK", live: false },
  { id: "okc" as const, name: "Oklahoma City", state: "OK", live: false },
];

export const RESTAURANTS: Restaurant[] = [
  {
    id: "mi-tierra",
    name: "Mi Tierra Cocina",
    slug: "mi-tierra-cocina",
    city: "dallas",
    neighborhood: "Oak Cliff",
    cuisine: "mexican",
    tagline: "Home-style Mexican, made with heart",
    story:
      "Family recipes, fresh salsas, and plates that taste like Sunday at abuela’s. Proudly local—join us for member-only kitchen specials.",
    hours: "Tue–Sun 11am–9pm",
    address: "Oak Cliff, Dallas, TX",
    lat: 32.735,
    lng: -96.82,
    emoji: "🌮",
    accent: "#e85d04",
    plateRating: 4.7,
    reviewCount: 128,
    acceptsReservations: false,
    acceptsOnlineOrders: true,
    approved: true,
    deals: [
      {
        id: "mt-free-fries",
        restaurantId: "mi-tierra",
        title: "Free side of fries",
        description: "With any entrée for members. In-store redeem.",
        type: "free_item",
        value: null,
        memberOnly: true,
        excludesAlcohol: true,
        active: true,
      },
      {
        id: "mt-25",
        restaurantId: "mi-tierra",
        title: "25% off your plate",
        description: "Percent off applies to member items only—not alcohol.",
        type: "percent_off",
        value: 25,
        memberOnly: true,
        excludesAlcohol: true,
        active: true,
      },
    ],
    menu: [
      {
        id: "mt-tacos",
        name: "Street tacos (3)",
        description: "Choice of carne asada, al pastor, or chicken",
        priceUsd: 12.5,
        category: "Mains",
        imageEmoji: "🌮",
      },
      {
        id: "mt-ench",
        name: "Enchilada plate",
        description: "Two enchiladas, rice, beans",
        priceUsd: 14,
        category: "Mains",
        imageEmoji: "🫔",
      },
      {
        id: "mt-fries",
        name: "Loaded fries",
        description: "Cotija, crema, pico",
        priceUsd: 7,
        category: "Sides",
        imageEmoji: "🍟",
      },
      {
        id: "mt-agua",
        name: "Agua fresca",
        description: "Horchata or jamaica",
        priceUsd: 3.5,
        category: "Drinks",
        imageEmoji: "🥤",
      },
    ],
  },
  {
    id: "andolinis",
    name: "Andolini’s Pizza",
    slug: "andolinis-pizza",
    city: "dallas",
    neighborhood: "Deep Ellum",
    cuisine: "pizza",
    tagline: "Serious slices, serious vibe",
    story:
      "Hand-tossed pies and a neighborhood energy. Member BOGOs that actually bring people back.",
    hours: "Daily 11am–11pm",
    address: "Deep Ellum, Dallas, TX",
    lat: 32.784,
    lng: -96.782,
    emoji: "🍕",
    accent: "#c1121f",
    plateRating: 4.5,
    reviewCount: 96,
    acceptsReservations: false,
    acceptsOnlineOrders: true,
    approved: true,
    deals: [
      {
        id: "an-bogo",
        restaurantId: "andolinis",
        title: "BOGO slice",
        description: "Buy one slice, get one free for members.",
        type: "bogo",
        value: null,
        memberOnly: true,
        excludesAlcohol: true,
        active: true,
      },
    ],
    menu: [
      {
        id: "an-pep",
        name: "Pepperoni slice",
        description: "Classic, crispy edge",
        priceUsd: 4.5,
        category: "Slices",
        imageEmoji: "🍕",
      },
      {
        id: "an-marg",
        name: "Margherita pie",
        description: "12\" fresh mozzarella, basil",
        priceUsd: 16,
        category: "Pies",
        imageEmoji: "🍕",
      },
      {
        id: "an-salad",
        name: "House salad",
        description: "Greens, vinaigrette",
        priceUsd: 8,
        category: "Sides",
        imageEmoji: "🥗",
      },
    ],
  },
  {
    id: "alpha-grill",
    name: "Alpha Grill",
    slug: "alpha-grill",
    city: "dallas",
    neighborhood: "South Dallas",
    cuisine: "bbq",
    tagline: "Smoke, sauce, and second helpings",
    story:
      "Low and slow BBQ with a local following. Members get real cuts of the action—not coupon noise.",
    hours: "Wed–Sun 12pm–8pm",
    address: "South Dallas, TX",
    lat: 32.73,
    lng: -96.78,
    emoji: "🍖",
    accent: "#6b4226",
    plateRating: 4.8,
    reviewCount: 210,
    acceptsReservations: false,
    acceptsOnlineOrders: true,
    approved: true,
    deals: [
      {
        id: "ag-50",
        restaurantId: "alpha-grill",
        title: "50% off sandwich",
        description: "Any BBQ sandwich for members. Member item only.",
        type: "percent_off",
        value: 50,
        memberOnly: true,
        excludesAlcohol: true,
        active: true,
      },
    ],
    menu: [
      {
        id: "ag-brisket",
        name: "Brisket sandwich",
        description: "Chopped, pickles, onions",
        priceUsd: 13,
        category: "Mains",
        imageEmoji: "🥪",
      },
      {
        id: "ag-ribs",
        name: "Half rack ribs",
        description: "Dry rub + house sauce",
        priceUsd: 18,
        category: "Mains",
        imageEmoji: "🍖",
      },
      {
        id: "ag-beans",
        name: "BBQ beans",
        description: "Side",
        priceUsd: 4,
        category: "Sides",
        imageEmoji: "🫘",
      },
    ],
  },
  {
    id: "just-winging",
    name: "Just Winging It",
    slug: "just-winging-it",
    city: "dallas",
    neighborhood: "East Dallas",
    cuisine: "wings",
    tagline: "Wings with zero hesitation",
    story: "Crispy wings, bold sauces, late-night energy. Members fly free on select flavors.",
    hours: "Daily 3pm–12am",
    address: "East Dallas, TX",
    lat: 32.81,
    lng: -96.74,
    emoji: "🍗",
    accent: "#ff6b35",
    plateRating: 4.4,
    reviewCount: 74,
    acceptsReservations: false,
    acceptsOnlineOrders: true,
    approved: true,
    deals: [
      {
        id: "jw-free-ice",
        restaurantId: "just-winging",
        title: "Free soft-serve",
        description: "With any 10-piece wing order for members.",
        type: "free_item",
        value: null,
        memberOnly: true,
        excludesAlcohol: true,
        active: true,
      },
    ],
    menu: [
      {
        id: "jw-10",
        name: "10-piece wings",
        description: "Choose heat level",
        priceUsd: 14,
        category: "Wings",
        imageEmoji: "🍗",
      },
      {
        id: "jw-fries",
        name: "Seasoned fries",
        description: "Basket",
        priceUsd: 5,
        category: "Sides",
        imageEmoji: "🍟",
      },
      {
        id: "jw-ice",
        name: "Soft-serve",
        description: "Vanilla swirl",
        priceUsd: 3,
        category: "Dessert",
        imageEmoji: "🍦",
      },
    ],
  },
  {
    id: "food-factory",
    name: "Food Factory",
    slug: "food-factory",
    city: "dallas",
    neighborhood: "Design District",
    cuisine: "american",
    tagline: "Build-your-own bowls & comfort classics",
    story:
      "Fast-casual energy with chef-level care. Member deals rotate so regulars always have a reason to come back.",
    hours: "Mon–Sat 10am–9pm",
    address: "Design District, Dallas, TX",
    lat: 32.79,
    lng: -96.83,
    emoji: "🏭",
    accent: "#2a9d8f",
    plateRating: 4.3,
    reviewCount: 55,
    acceptsReservations: true,
    acceptsOnlineOrders: true,
    approved: true,
    deals: [
      {
        id: "ff-20",
        restaurantId: "food-factory",
        title: "20% off bowl",
        description: "Any build-your-own bowl for members.",
        type: "percent_off",
        value: 20,
        memberOnly: true,
        excludesAlcohol: true,
        active: true,
      },
    ],
    menu: [
      {
        id: "ff-bowl",
        name: "Signature bowl",
        description: "Base + protein + 3 toppings",
        priceUsd: 13.5,
        category: "Bowls",
        imageEmoji: "🥣",
      },
      {
        id: "ff-burger",
        name: "Factory burger",
        description: "Smash style, house sauce",
        priceUsd: 12,
        category: "Mains",
        imageEmoji: "🍔",
      },
    ],
  },
  {
    id: "prossimos",
    name: "Prossimo’s",
    slug: "prossimos",
    city: "dallas",
    neighborhood: "Uptown",
    cuisine: "italian",
    tagline: "Italian comfort, neighborhood table",
    story:
      "Pasta, wine, and long conversations. Members get the off-menu treatment—free item or percent, your call on the night.",
    hours: "Tue–Sun 5pm–10pm",
    address: "Uptown, Dallas, TX",
    lat: 32.8,
    lng: -96.8,
    emoji: "🍝",
    accent: "#457b9d",
    plateRating: 4.6,
    reviewCount: 88,
    acceptsReservations: true,
    acceptsOnlineOrders: true,
    approved: true,
    deals: [
      {
        id: "pr-bogo",
        restaurantId: "prossimos",
        title: "BOGO appetizer",
        description: "Buy one app, get one free for members.",
        type: "bogo",
        value: null,
        memberOnly: true,
        excludesAlcohol: true,
        active: true,
      },
    ],
    menu: [
      {
        id: "pr-pasta",
        name: "Cacio e pepe",
        description: "Classic Roman-style",
        priceUsd: 17,
        category: "Pasta",
        imageEmoji: "🍝",
      },
      {
        id: "pr-app",
        name: "Bruschetta",
        description: "Tomato, basil, olive oil",
        priceUsd: 9,
        category: "Apps",
        imageEmoji: "🍞",
      },
      {
        id: "pr-tir",
        name: "Tiramisu",
        description: "House-made",
        priceUsd: 8,
        category: "Dessert",
        imageEmoji: "🍰",
      },
    ],
  },
];

export const REVIEWS: Review[] = [
  {
    id: "r1",
    restaurantId: "mi-tierra",
    author: "Alex M.",
    plates: 5,
    text: "Member free fries + killer tacos. Worth the pass alone.",
    createdAt: "2026-07-20",
  },
  {
    id: "r2",
    restaurantId: "alpha-grill",
    author: "Jordan K.",
    plates: 5,
    text: "50% sandwich deal is unfair (in a good way).",
    createdAt: "2026-07-28",
  },
  {
    id: "r3",
    restaurantId: "andolinis",
    author: "Sam R.",
    plates: 4,
    text: "BOGO slice after work. Deep Ellum win.",
    createdAt: "2026-08-01",
  },
];

export const FEED_POSTS: FeedPost[] = [
  {
    id: "p1",
    city: "dallas",
    author: "Maya",
    title: "Best late-night wings under a member deal?",
    body: "Looking for spicy + a free dessert hook. Where are y’all going?",
    createdAt: "2026-08-02T18:00:00Z",
    replies: [
      {
        id: "p1r1",
        author: "Chris",
        body: "Just Winging It — free soft-serve with 10pc. Go.",
        createdAt: "2026-08-02T18:20:00Z",
      },
      {
        id: "p1r2",
        author: "Priya",
        body: "Second that. Redeem QR took 5 seconds.",
        createdAt: "2026-08-02T19:05:00Z",
      },
    ],
  },
  {
    id: "p2",
    city: "dallas",
    author: "Diego",
    title: "Oak Cliff taco crawl this weekend",
    body: "Starting at Mi Tierra. Anyone want to split a table? Members only vibes.",
    createdAt: "2026-08-03T12:00:00Z",
    replies: [],
  },
];

export function getRestaurant(id: string) {
  return RESTAURANTS.find((r) => r.id === id || r.slug === id);
}

export function getDeal(dealId: string) {
  for (const r of RESTAURANTS) {
    const d = r.deals.find((x) => x.id === dealId);
    if (d) return { deal: d, restaurant: r };
  }
  return null;
}

export function cuisineLabel(c: string) {
  const map: Record<string, string> = {
    mexican: "Mexican",
    italian: "Italian",
    bbq: "BBQ",
    american: "American",
    wings: "Wings",
    pizza: "Pizza",
    other: "Other",
  };
  return map[c] ?? c;
}

export const PARTNER_EVENTS: import("./types").PartnerEvent[] = [
  {
    id: "ev1",
    restaurantId: "mi-tierra",
    restaurantName: "Mi Tierra Cocina",
    title: "Taco Tuesday Member Night",
    description: "Live salsa, member-only free guac upgrade, and kitchen tours at 7pm.",
    date: "2026-08-12",
    time: "5:00 PM - 9:00 PM",
    city: "dallas",
    emoji: "🌮",
    address: "Oak Cliff, Dallas, TX",
    ticketUrl: "https://example.com/tickets/mi-tierra-taco-tuesday",
    ticketPriceUsd: 0,
  },
  {
    id: "ev2",
    restaurantId: "andolinis",
    restaurantName: "Andolini's Pizza",
    title: "Deep Ellum Slice Social",
    description: "Meet other members, BOGO slice special all night, outdoor seating.",
    date: "2026-08-16",
    time: "6:00 PM - 10:00 PM",
    city: "dallas",
    emoji: "🍕",
    address: "Deep Ellum, Dallas, TX",
    ticketUrl: "https://example.com/tickets/andolinis-slice-social",
    ticketPriceUsd: 15,
  },
  {
    id: "ev3",
    restaurantId: "alpha-grill",
    restaurantName: "Alpha Grill",
    title: "Smokehouse Saturday",
    description: "Pit-master demo, sample flights, and member sandwich deal.",
    date: "2026-08-23",
    time: "12:00 PM - 4:00 PM",
    city: "dallas",
    emoji: "🍖",
    address: "South Dallas, TX",
    ticketUrl: "https://example.com/tickets/alpha-smokehouse",
    ticketPriceUsd: 25,
  },
  {
    id: "ev4",
    restaurantId: "prossimos",
    restaurantName: "Prossimo's",
    title: "Pasta & Plates Night",
    description: "Chef table for members. RSVP in app. Wine pairings optional.",
    date: "2026-08-28",
    time: "7:00 PM - 10:00 PM",
    city: "dallas",
    emoji: "🍝",
    address: "Uptown, Dallas, TX",
    ticketUrl: "https://example.com/tickets/prossimos-pasta-night",
    ticketPriceUsd: 45,
  },
];

export const JOB_POSTINGS: import("./types").JobPosting[] = [
  {
    id: "job1",
    restaurantId: "mi-tierra",
    restaurantName: "Mi Tierra Cocina",
    title: "Line Cook",
    description: "Evening shifts, experience with high-volume Mexican preferred. Tips + hourly.",
    type: "full-time",
    city: "dallas",
    postedAt: "2026-08-01",
    payRange: "$16-$20/hr",
    applyUrl: "https://example.com/careers/mi-tierra/line-cook",
  },
  {
    id: "job2",
    restaurantId: "andolinis",
    restaurantName: "Andolini's Pizza",
    title: "Front of House / Server",
    description: "Nights & weekends in Deep Ellum. Great for students. Member-deal friendly team.",
    type: "part-time",
    city: "dallas",
    postedAt: "2026-08-02",
    payRange: "$12/hr + tips",
    applyUrl: "https://example.com/careers/andolinis/server",
  },
  {
    id: "job3",
    restaurantId: "alpha-grill",
    restaurantName: "Alpha Grill",
    title: "Pit Assistant",
    description: "Learn real BBQ. Early mornings, weekend events. Training provided.",
    type: "part-time",
    city: "dallas",
    postedAt: "2026-08-03",
    payRange: "$15-$18/hr",
    applyUrl: "https://example.com/careers/alpha-grill/pit-assistant",
  },
  {
    id: "job4",
    restaurantId: "just-winging",
    restaurantName: "Just Winging It",
    title: "Delivery Runner (event nights)",
    description: "Seasonal help for busy wings nights. Flexible schedule.",
    type: "gig",
    city: "dallas",
    postedAt: "2026-08-04",
    payRange: "$14/hr + mileage",
    applyUrl: "https://example.com/careers/just-winging/runner",
  },
];