import type { AuthAccount, Restaurant } from "./types";

/** Public business details for Tulsa-area spots. No invented member discounts. */
export const TULSA_RESTAURANTS: Restaurant[] = [
  {
    id: "food-factory",
    name: "IM Food Factory",
    slug: "im-food-factory",
    city: "tulsa",
    neighborhood: "East Tulsa",
    cuisine: "american",
    tagline: "Burgers and The Cure Food, on South Mingo",
    story:
      "Food Factory Burgers and The Cure Food share the counter at 6217 S Mingo Rd. Dinner is Tuesday–Sunday 5pm–10:30pm, with lunch Tuesday–Saturday 10am–2pm. Phone 539-766-0614.",
    hours: "Tue–Sat 10am–2pm and 5pm–10:30pm; Sun 5pm–10:30pm; Mon closed",
    address: "6217 S Mingo Rd, Tulsa, OK 74133",
    lat: 36.073,
    lng: -95.8685,
    emoji: "🍔",
    accent: "#2a9d8f",
    plateRating: 0,
    reviewCount: 0,
    acceptsReservations: false,
    acceptsOnlineOrders: true,
    approved: true,
    deals: [],
    menu: [
      {
        id: "ff-burger",
        name: "Food Factory burger",
        description: "House burger from the Food Factory Burgers menu",
        priceUsd: 0,
        category: "Mains",
        imageEmoji: "🍔",
      },
    ],
  },
  {
    id: "alpha-grill",
    name: "Alpha Grill BBQ",
    slug: "alpha-grill-bbq",
    city: "tulsa",
    neighborhood: "Southern Hills",
    cuisine: "bbq",
    tagline: "Slow-smoked barbecue on South Lewis",
    story:
      "Alpha Grill BBQ serves smoked brisket, ribs, pulled pork, and scratch-made sides at 6670 S Lewis Ave #102. Open Wednesday–Sunday 11am–9pm. Phone (918) 621-8788.",
    hours: "Wed–Sun 11am–9pm; Mon–Tue closed",
    address: "6670 S Lewis Ave #102, Tulsa, OK 74136",
    lat: 36.0660755,
    lng: -95.958573,
    emoji: "🍖",
    accent: "#b45309",
    plateRating: 0,
    reviewCount: 0,
    acceptsReservations: false,
    acceptsOnlineOrders: true,
    approved: true,
    deals: [],
    menu: [
      {
        id: "ag-brisket",
        name: "Smoked brisket",
        description: "Sliced brisket from the daily smoke",
        priceUsd: 0,
        category: "Mains",
        imageEmoji: "🍖",
      },
    ],
  },
  {
    id: "just-winging",
    name: "Brothers Just Wingin’ It",
    slug: "brothers-just-wingin-it",
    city: "tulsa",
    neighborhood: "East Tulsa",
    cuisine: "wings",
    tagline: "Scratch-made wings from the family truck",
    story:
      "Brothers Just Wingin’ It (also called Mr. & Mrs. Just Wingin’ It) is a Tulsa wing truck. A listed stop is 8601 S Mingo Rd. Yelp hours: Wed 12–7, Thu 2–8, Fri 3–9, Sat 12–8. Phone (918) 282-9339. The truck also posts weekly locations.",
    hours: "Wed 12pm–7pm; Thu 2pm–8pm; Fri 3pm–9pm; Sat 12pm–8pm",
    address: "8601 S Mingo Rd, Tulsa, OK 74133",
    lat: 36.038,
    lng: -95.8685,
    emoji: "🍗",
    accent: "#e85d04",
    plateRating: 0,
    reviewCount: 0,
    acceptsReservations: false,
    acceptsOnlineOrders: true,
    approved: true,
    deals: [],
    menu: [
      {
        id: "jw-wings",
        name: "Bone-in wings",
        description: "House flavors, including Mama’s Classic",
        priceUsd: 0,
        category: "Mains",
        imageEmoji: "🍗",
      },
    ],
  },
  {
    id: "prossimos",
    name: "Prossimo Ristorante",
    slug: "prossimo-ristorante",
    city: "tulsa",
    neighborhood: "Cherry Street",
    cuisine: "italian",
    tagline: "Amalfi Coast pasta on Cherry Street",
    story:
      "Prossimo serves light, artful pasta with seafood and vegetables at 1550 E 15th St. Hours: Mon–Thu 11am–10pm, Fri 11am–11pm, Sat 10am–11pm, Sun 10am–10pm. Phone (918) 271-5096.",
    hours: "Mon–Thu 11am–10pm; Fri 11am–11pm; Sat 10am–11pm; Sun 10am–10pm",
    address: "1550 E 15th St, Tulsa, OK 74120",
    lat: 36.1405463,
    lng: -95.970341,
    emoji: "🍝",
    accent: "#457b9d",
    plateRating: 0,
    reviewCount: 0,
    acceptsReservations: true,
    acceptsOnlineOrders: true,
    approved: true,
    deals: [],
    menu: [
      {
        id: "pr-mozz",
        name: "Fresh mozzarella",
        description: "Hand-pulled mozzarella with olive oil",
        priceUsd: 21,
        category: "Apps",
        imageEmoji: "🧀",
      },
    ],
  },
  {
    id: "tacos-x-mezcal",
    name: "Tacos x Mezcal",
    slug: "tacos-x-mezcal",
    city: "tulsa",
    neighborhood: "SoBo",
    cuisine: "mexican",
    tagline: "Nayarit-style street tacos and agave",
    story:
      "Tacos x Mezcal is at 39 E 18th St in the SoBo district. Tuesday–Wednesday 5pm–10pm, Thursday–Saturday 11am–10pm, Sunday 11am–9pm, Monday closed. Phone (918) 764-8666.",
    hours: "Tue–Wed 5pm–10pm; Thu–Sat 11am–10pm; Sun 11am–9pm; Mon closed",
    address: "39 E 18th St, Tulsa, OK 74119",
    lat: 36.136146,
    lng: -95.985479,
    emoji: "🌮",
    accent: "#c1121f",
    plateRating: 0,
    reviewCount: 0,
    acceptsReservations: true,
    acceptsOnlineOrders: true,
    approved: true,
    deals: [],
    menu: [
      {
        id: "tx-elote",
        name: "Mexican street elote bowl",
        description: "Butter, chipotle aioli, cotija, lime",
        priceUsd: 8.25,
        category: "Apps",
        imageEmoji: "🌽",
      },
      {
        id: "tx-guac",
        name: "Traditional guacamole",
        description: "Radish, cucumber, cilantro, onion, jalapeño, tomato",
        priceUsd: 11,
        category: "Apps",
        imageEmoji: "🥑",
      },
    ],
  },
  {
    id: "kremee",
    name: "Kremee Taiyaki and Ice Cream",
    slug: "kremee",
    city: "tulsa",
    neighborhood: "East Tulsa",
    cuisine: "other",
    tagline: "Soft serve, milkshakes, and taiyaki",
    story:
      "Kremee serves soft-serve, milkshakes, and taiyaki at 8316 E 61st St, Suite 106. Open Monday and Wednesday–Thursday 12pm–9pm, Friday–Saturday 12pm–10pm, Sunday 12pm–9pm. Tuesday closed. Phone (918) 749-1111.",
    hours: "Mon, Wed–Thu, Sun 12pm–9pm; Fri–Sat 12pm–10pm; Tue closed",
    address: "8316 E 61st St, Ste 106, Tulsa, OK 74133",
    lat: 36.074783,
    lng: -95.883771,
    emoji: "🍦",
    accent: "#f4a261",
    plateRating: 0,
    reviewCount: 0,
    acceptsReservations: false,
    acceptsOnlineOrders: true,
    approved: true,
    deals: [],
    menu: [
      {
        id: "kr-soft",
        name: "Soft serve",
        description: "House soft serve, including Hokkaido milk",
        priceUsd: 0,
        category: "Dessert",
        imageEmoji: "🍦",
      },
      {
        id: "kr-taiyaki",
        name: "Taiyaki",
        description: "Fish-shaped cake with a sweet filling",
        priceUsd: 0,
        category: "Dessert",
        imageEmoji: "🐟",
      },
    ],
  },
  {
    id: "boujee-delights",
    name: "Boujee Delights",
    slug: "boujee-delights",
    city: "tulsa",
    neighborhood: "Skiatook",
    cuisine: "other",
    tagline: "Shaved ice, Dole Whip, and loaded teas",
    story:
      "Boujee Delights is a snack shop in the Tulsa area at 214 S Locust St, Skiatook. Shaved ice, Dole Whip, ice cream, smoothies, and loaded teas. Phone (918) 313-3785. Hours posted on Yelp: Mon–Thu and Sun 12pm–8:30pm, Fri 12pm–9pm, Sat 2pm–9pm.",
    hours: "Mon–Thu 12pm–8:30pm; Fri 12pm–9pm; Sat 2pm–9pm; Sun 12pm–8:30pm",
    address: "214 S Locust St, Skiatook, OK 74070",
    lat: 36.3684042,
    lng: -96.0055555,
    emoji: "🍧",
    accent: "#db2777",
    plateRating: 0,
    reviewCount: 0,
    acceptsReservations: false,
    acceptsOnlineOrders: false,
    approved: true,
    deals: [],
    menu: [
      {
        id: "bd-ice",
        name: "Shaved ice",
        description: "House shaved ice",
        priceUsd: 0,
        category: "Dessert",
        imageEmoji: "🍧",
      },
    ],
  },
  {
    id: "coffee-grinder",
    name: "The Coffee Grinder",
    slug: "the-coffee-grinder",
    city: "tulsa",
    neighborhood: "Sheridan",
    cuisine: "american",
    tagline: "Coffee and pastries on South Sheridan",
    story:
      "The Coffee Grinder is a café at 5233 S Sheridan Rd, Tulsa. Fresh coffee and pastries. Confirm today’s hours at the shop before you go.",
    hours: "See the café for today’s hours",
    address: "5233 S Sheridan Rd, Tulsa, OK 74145",
    lat: 36.087,
    lng: -95.9045,
    emoji: "☕",
    accent: "#6f4e37",
    plateRating: 0,
    reviewCount: 0,
    acceptsReservations: false,
    acceptsOnlineOrders: false,
    approved: true,
    deals: [],
    menu: [
      {
        id: "cg-drip",
        name: "Drip coffee",
        description: "House brewed coffee",
        priceUsd: 0,
        category: "Drinks",
        imageEmoji: "☕",
      },
    ],
  },
  {
    id: "andolinis",
    name: "Andolini’s Pizzeria",
    slug: "andolinis-pizzeria",
    city: "tulsa",
    neighborhood: "Cherry Street",
    cuisine: "pizza",
    tagline: "Cherry Street pies next door to Prossimo",
    story:
      "Andolini’s Pizzeria on Cherry Street is at 1552 E 15th St, Tulsa. Neighborhood pizzas and a full pie menu. Phone is listed with the restaurant.",
    hours: "Daily 11am–11pm",
    address: "1552 E 15th St, Tulsa, OK 74120",
    lat: 36.1404253,
    lng: -95.9697367,
    emoji: "🍕",
    accent: "#c1121f",
    plateRating: 0,
    reviewCount: 0,
    acceptsReservations: false,
    acceptsOnlineOrders: true,
    approved: true,
    deals: [],
    menu: [
      {
        id: "an-pie",
        name: "House pizza",
        description: "Cherry Street pie",
        priceUsd: 0,
        category: "Mains",
        imageEmoji: "🍕",
      },
    ],
  },
  {
    id: "casa-arepa",
    name: "El Arepaso Venezuelan Cafe",
    slug: "el-arepaso",
    city: "tulsa",
    neighborhood: "Yale",
    cuisine: "latin",
    tagline: "Venezuelan arepas, empanadas, and coffee",
    story:
      "El Arepaso Venezuelan Cafe is at 8036 S Yale Ave, Tulsa. Phone (918) 430-3136. A recent public listing shows Sunday 10am–6pm and Monday–Saturday 11am–8pm.",
    hours: "Sun 10am–6pm; Mon–Sat 11am–8pm",
    address: "8036 S Yale Ave, Tulsa, OK 74136",
    lat: 36.0470255,
    lng: -95.9236039,
    emoji: "🫓",
    accent: "#f4a261",
    plateRating: 0,
    reviewCount: 0,
    acceptsReservations: false,
    acceptsOnlineOrders: true,
    approved: true,
    deals: [],
    menu: [
      {
        id: "ca-arepa",
        name: "Arepa",
        description: "Venezuelan corn cake with a house filling",
        priceUsd: 0,
        category: "Mains",
        imageEmoji: "🫓",
      },
    ],
  },
  {
    id: "mi-tierra",
    name: "Mi Tierra Cocina Mexicana",
    slug: "mi-tierra-cocina-mexicana",
    city: "tulsa",
    neighborhood: "KingsPoint Village",
    cuisine: "mexican",
    tagline: "Family-style Mexican kitchen on South Yale",
    story:
      "Mi Tierra Cocina Mexicana’s KingsPoint Village location is at 6030 S Yale Ave, Tulsa. The family also has kitchens at 9521 Riverside Parkway and in Glenpool. Tulsa World listed hours as 11am–10pm daily. Phone 539-215-6974.",
    hours: "Daily 11am–10pm",
    address: "6030 S Yale Ave, Tulsa, OK 74136",
    lat: 36.0735,
    lng: -95.9223,
    emoji: "🌮",
    accent: "#e85d04",
    plateRating: 0,
    reviewCount: 0,
    acceptsReservations: false,
    acceptsOnlineOrders: true,
    approved: true,
    deals: [],
    menu: [
      {
        id: "mt-ench",
        name: "Enchiladas chipotle",
        description: "House specialty",
        priceUsd: 0,
        category: "Mains",
        imageEmoji: "🌮",
      },
    ],
  },
];

export const DEMO_PARTNER_PASSWORD = "demo1234";

export function tulsaPartnerAccounts(): AuthAccount[] {
  return TULSA_PARTNER_LOGINS.map(([id, slug]) => {
    const restaurant = TULSA_RESTAURANTS.find((r) => r.id === id);
    return {
      id: `partner-${id}`,
      email: `${slug}@gorditopass.local`,
      password: DEMO_PARTNER_PASSWORD,
      role: "restaurant" as const,
      name: `${restaurant?.name ?? id} Owner`,
      city: "tulsa" as const,
      isMember: false,
      planId: null,
      familySeats: 1,
      maxFamilySeats: 6,
      staffRole: "owner" as const,
      restaurantId: id,
      createdAt: "2026-09-25T00:00:00.000Z",
    };
  });
}

export const TULSA_PARTNER_LOGINS = [
  ["food-factory", "foodfactory"],
  ["alpha-grill", "alphagrill"],
  ["just-winging", "justwinginit"],
  ["prossimos", "prossimo"],
  ["tacos-x-mezcal", "tacosxmezcal"],
  ["kremee", "kremee"],
  ["boujee-delights", "boujee"],
  ["coffee-grinder", "coffeegrinder"],
  ["andolinis", "andolinis"],
  ["casa-arepa", "elarepaso"],
  ["mi-tierra", "mitierra"],
] as const;
