import type { AuthAccount, Restaurant } from "./types";

/** Public business details for Tulsa-area spots. No invented member discounts. */
export const TULSA_RESTAURANTS: Restaurant[] = [
  {
    id: "food-factory",
    name: "IM Food Factory",
    slug: "im-food-factory",
    city: "tulsa",
    neighborhood: "East Tulsa",
    cuisine: "american",
    tagline: "Burgers and The Cure Food, on South Mingo",
    story:
      "Food Factory Burgers and The Cure Food share the counter at 6217 S Mingo Rd. Dinner is Tuesday–Sunday 5pm–10:30pm, with lunch Tuesday–Saturday 10am–2pm. Phone 539-766-0614.",
    hours: "Tue–Sat 10am–2pm and 5pm–10:30pm; Sun 5pm–10:30pm; Mon closed",
    address: "6217 S Mingo Rd, Tulsa, OK 74133",
    lat: 36.073,
    lng: -95.8685,
    emoji: "🍔",
    logoUrl: "/restaurants/food.png",
    accent: "#2a9d8f",
    plateRating: 0,
    reviewCount: 0,
    acceptsReservations: false,
    acceptsOnlineOrders: true,
    approved: true,
    deals: [],
    menu: [
      { id: "ff-moz", name: "Mozzarella flatbread pizza", description: "Seasoned flatbread, mozzarella, ranch", priceUsd: 8.03, category: "Pizza", imageEmoji: "🍕" },
      { id: "ff-cbr", name: "Chicken bacon ranch flatbread", description: "Chicken, bacon, ranch, no pizza sauce", priceUsd: 9.18, category: "Pizza", imageEmoji: "🍕" },
      { id: "ff-pep", name: "Pepperoni flatbread pizza", description: "Pepperoni, mozzarella, ranch", priceUsd: 10.33, category: "Pizza", imageEmoji: "🍕" },
      { id: "ff-burger", name: "Food Factory burger", description: "From the Food Factory Burgers menu", priceUsd: 0, category: "Burgers", imageEmoji: "🍔" },
    ],
  },
  {
    id: "alpha-grill",
    name: "Alpha Grill BBQ",
    slug: "alpha-grill-bbq",
    city: "tulsa",
    neighborhood: "Southern Hills",
    cuisine: "bbq",
    tagline: "Slow-smoked barbecue on South Lewis",
    story:
      "Alpha Grill BBQ serves smoked brisket, ribs, pulled pork, and scratch-made sides at 6670 S Lewis Ave #102. Open Wednesday–Sunday 11am–9pm. Phone (918) 621-8788.",
    hours: "Wed–Sun 11am–9pm; Mon–Tue closed",
    address: "6670 S Lewis Ave #102, Tulsa, OK 74136",
    lat: 36.0660755,
    lng: -95.958573,
    emoji: "🍖",
    logoUrl: "/restaurants/alpha.png",
    accent: "#b45309",
    plateRating: 0,
    reviewCount: 0,
    acceptsReservations: false,
    acceptsOnlineOrders: true,
    approved: true,
    deals: [],
    menu: [
      { id: "ag-lunch", name: "Lunch combo", description: "11am–2pm combo", priceUsd: 9.99, category: "Lunch", imageEmoji: "🍖" },
      { id: "ag-happy", name: "Happy hour plate", description: "3pm–6pm", priceUsd: 7.99, category: "Lunch", imageEmoji: "🍖" },
      { id: "ag-burrito", name: "Alpha burrito", description: "Brisket, mac and cheese, and BBQ sauce", priceUsd: 17.99, category: "Plates", imageEmoji: "🌯" },
      { id: "ag-sundae", name: "BBQ sundae", description: "Two meats on potato salad, slaw, and BBQ beans", priceUsd: 14.99, category: "Plates", imageEmoji: "🍖" },
      { id: "ag-baby", name: "Baby Fatt Alpha potato", description: "Three meats and 2 ribs", priceUsd: 25.99, category: "Family", imageEmoji: "🥔" },
      { id: "ag-pac", name: "Alpha PAC", description: "Half rack of ribs and a quarter pound of four meats", priceUsd: 44.99, category: "Family", imageEmoji: "🍖" },
      { id: "ag-thepac", name: "The PAC", description: "Half rack, half pound of four meats, two family sides", priceUsd: 61.99, category: "Family", imageEmoji: "🍖" },
      { id: "ag-feast", name: "Alpha Feast", description: "Full rack, a pound of six meats, and a pint of every side", priceUsd: 155.99, category: "Family", imageEmoji: "🍖" },
      { id: "ag-cobbler", name: "Smoked peach cobbler", description: "Dessert", priceUsd: 4.99, category: "Dessert", imageEmoji: "🍑" },
    ],
  },
  {
    id: "just-winging",
    name: "Brothers Just Wingin’ It",
    slug: "brothers-just-wingin-it",
    city: "tulsa",
    neighborhood: "East Tulsa",
    cuisine: "wings",
    tagline: "Scratch-made wings from the family truck",
    story:
      "Brothers Just Wingin’ It (also called Mr. & Mrs. Just Wingin’ It) is a Tulsa wing truck. A listed stop is 8601 S Mingo Rd. Yelp hours: Wed 12–7, Thu 2–8, Fri 3–9, Sat 12–8. Phone (918) 282-9339. The truck also posts weekly locations.",
    hours: "Wed 12pm–7pm; Thu 2pm–8pm; Fri 3pm–9pm; Sat 12pm–8pm",
    address: "8601 S Mingo Rd, Tulsa, OK 74133",
    lat: 36.038,
    lng: -95.8685,
    emoji: "🍗",
    accent: "#e85d04",
    plateRating: 0,
    reviewCount: 0,
    acceptsReservations: false,
    acceptsOnlineOrders: true,
    approved: true,
    deals: [],
    menu: [
      { id: "jw-mama", name: "Mama’s Classic wings", description: "Honey-glazed bone-in wings", priceUsd: 0, category: "Wings", imageEmoji: "🍗" },
      { id: "jw-lemon", name: "Lemon pepper ranch fusion", description: "Savory wing sauce", priceUsd: 0, category: "Wings", imageEmoji: "🍗" },
      { id: "jw-fries", name: "Seasoned fries", description: "Side", priceUsd: 0, category: "Sides", imageEmoji: "🍟" },
      { id: "jw-pop", name: "Jalapeño poppers", description: "Side", priceUsd: 0, category: "Sides", imageEmoji: "🌶️" },
    ],
  },
  {
    id: "prossimos",
    name: "Prossimo Ristorante",
    slug: "prossimo-ristorante",
    city: "tulsa",
    neighborhood: "Cherry Street",
    cuisine: "italian",
    tagline: "Amalfi Coast pasta on Cherry Street",
    story:
      "Prossimo serves light, artful pasta with seafood and vegetables at 1550 E 15th St. Hours: Mon–Thu 11am–10pm, Fri 11am–11pm, Sat 10am–11pm, Sun 10am–10pm. Phone (918) 271-5096.",
    hours: "Mon–Thu 11am–10pm; Fri 11am–11pm; Sat 10am–11pm; Sun 10am–10pm",
    address: "1550 E 15th St, Tulsa, OK 74120",
    lat: 36.1405463,
    lng: -95.970341,
    emoji: "🍝",
    logoUrl: "/restaurants/prossimo.png",
    accent: "#457b9d",
    plateRating: 0,
    reviewCount: 0,
    acceptsReservations: true,
    acceptsOnlineOrders: true,
    approved: true,
    deals: [],
    menu: [
      { id: "pr-cal", name: "Calamari", description: "Spicy marinara and caper aioli", priceUsd: 19, category: "Apps", imageEmoji: "🦑" },
      { id: "pr-mozz", name: "Fresh mozzarella", description: "Hand-pulled, olive oil, Himalayan salt", priceUsd: 21, category: "Apps", imageEmoji: "🧀" },
      { id: "pr-flat", name: "Grilled flatbread", description: "Caponata and aged balsamic", priceUsd: 17, category: "Apps", imageEmoji: "🍞" },
      { id: "pr-pol", name: "Polenta and meatballs", description: "San Marzano marinara and Parmigiano", priceUsd: 18, category: "Apps", imageEmoji: "🍝" },
      { id: "pr-marrow", name: "Bone marrow", description: "Starter", priceUsd: 19, category: "Apps", imageEmoji: "🍽️" },
      { id: "pr-gnocchi", name: "Pesto gnocchi", description: "Entrée", priceUsd: 39, category: "Pasta", imageEmoji: "🍝" },
      { id: "pr-pac", name: "Vegan paccheri", description: "White wine, roasted garlic, baby kale", priceUsd: 32, category: "Pasta", imageEmoji: "🍝" },
      { id: "pr-spa", name: "Vegan spaghetti San Marzano", description: "Garlic marinara and aged balsamic", priceUsd: 28, category: "Pasta", imageEmoji: "🍝" },
    ],
  },
  {
    id: "tacos-x-mezcal",
    name: "Tacos x Mezcal",
    slug: "tacos-x-mezcal",
    city: "tulsa",
    neighborhood: "SoBo",
    cuisine: "mexican",
    tagline: "Nayarit-style street tacos and agave",
    story:
      "Tacos x Mezcal is at 39 E 18th St in the SoBo district. Tuesday–Wednesday 5pm–10pm, Thursday–Saturday 11am–10pm, Sunday 11am–9pm, Monday closed. Phone (918) 764-8666.",
    hours: "Tue–Wed 5pm–10pm; Thu–Sat 11am–10pm; Sun 11am–9pm; Mon closed",
    address: "39 E 18th St, Tulsa, OK 74119",
    lat: 36.136146,
    lng: -95.985479,
    emoji: "🌮",
    logoUrl: "/restaurants/txmz.png",
    accent: "#c1121f",
    plateRating: 0,
    reviewCount: 0,
    acceptsReservations: true,
    acceptsOnlineOrders: true,
    approved: true,
    deals: [],
    menu: [
      { id: "tx-elote", name: "Mexican street elote bowl", description: "Butter, chipotle aioli, cotija, lime", priceUsd: 8.25, category: "Apps", imageEmoji: "🌽" },
      { id: "tx-guac", name: "Traditional guacamole", description: "Radish, cucumber, cilantro, onion, jalapeño, tomato", priceUsd: 11, category: "Apps", imageEmoji: "🥑" },
      { id: "tx-chap", name: "Guacamole con chapulines", description: "Crispy seasoned crickets, radish, cucumber, tajín", priceUsd: 13.2, category: "Apps", imageEmoji: "🥑" },
      { id: "tx-queso", name: "Skillet queso fundido", description: "Queso Chihuahua, shallot, cilantro", priceUsd: 15.5, category: "Apps", imageEmoji: "🧀" },
      { id: "tx-birria", name: "Quesabirria", description: "Slow-roasted beef, queso, onion, cilantro, side of broth", priceUsd: 17, category: "Plates", imageEmoji: "🌮" },
      { id: "tx-oax", name: "Oaxaca bowl", description: "Flank steak, roasted corn, black beans, avocado, rice", priceUsd: 18.5, category: "Plates", imageEmoji: "🥣" },
      { id: "tx-tlayuda", name: "Tlayuda", description: "Large crisp tortilla", priceUsd: 23, category: "Plates", imageEmoji: "🌮" },
    ],
  },
  {
    id: "kremee",
    name: "Kremee Taiyaki and Ice Cream",
    slug: "kremee",
    city: "tulsa",
    neighborhood: "East Tulsa",
    cuisine: "other",
    tagline: "Soft serve, milkshakes, and taiyaki",
    story:
      "Kremee serves soft-serve, milkshakes, and taiyaki at 8316 E 61st St, Suite 106. Open Monday and Wednesday–Thursday 12pm–9pm, Friday–Saturday 12pm–10pm, Sunday 12pm–9pm. Tuesday closed. Phone (918) 749-1111.",
    hours: "Mon, Wed–Thu, Sun 12pm–9pm; Fri–Sat 12pm–10pm; Tue closed",
    address: "8316 E 61st St, Ste 106, Tulsa, OK 74133",
    lat: 36.074783,
    lng: -95.883771,
    emoji: "🍦",
    logoUrl: "/restaurants/kremee.png",
    accent: "#f4a261",
    plateRating: 0,
    reviewCount: 0,
    acceptsReservations: false,
    acceptsOnlineOrders: true,
    approved: true,
    deals: [],
    menu: [
      { id: "kr-soft", name: "Soft serve", description: "Warmer, fluffier soft serve. Flavors include Hokkaido milk", priceUsd: 0, category: "Ice cream", imageEmoji: "🍦" },
      { id: "kr-taiyaki", name: "Taiyaki", description: "Crisp fish-shaped waffle filled with soft serve", priceUsd: 0, category: "Taiyaki", imageEmoji: "🐟" },
      { id: "kr-shake", name: "Milkshake", description: "Hand-blended with soft serve and whipped cream", priceUsd: 0, category: "Shakes", imageEmoji: "🥤" },
    ],
  },
  {
    id: "boujee-delights",
    name: "Boujee Delights",
    slug: "boujee-delights",
    city: "tulsa",
    neighborhood: "Skiatook",
    cuisine: "other",
    tagline: "Shaved ice, Dole Whip, and loaded teas",
    story:
      "Boujee Delights is a snack shop in the Tulsa area at 214 S Locust St, Skiatook. Shaved ice, Dole Whip, ice cream, smoothies, and loaded teas. Phone (918) 313-3785. Hours posted on Yelp: Mon–Thu and Sun 12pm–8:30pm, Fri 12pm–9pm, Sat 2pm–9pm.",
    hours: "Mon–Thu 12pm–8:30pm; Fri 12pm–9pm; Sat 2pm–9pm; Sun 12pm–8:30pm",
    address: "214 S Locust St, Skiatook, OK 74070",
    lat: 36.3684042,
    lng: -96.0055555,
    emoji: "🍧",
    logoUrl: "/restaurants/boujee.jpg",
    accent: "#db2777",
    plateRating: 0,
    reviewCount: 0,
    acceptsReservations: false,
    acceptsOnlineOrders: false,
    approved: true,
    deals: [],
    menu: [
      { id: "bd-ice", name: "Shaved ice", description: "House shaved ice", priceUsd: 0, category: "Sweets", imageEmoji: "🍧" },
      { id: "bd-dole", name: "Dole Whip", description: "Pineapple and fudge brownie are among the flavors", priceUsd: 0, category: "Sweets", imageEmoji: "🍦" },
      { id: "bd-cream", name: "Ice cream", description: "Scooped ice cream", priceUsd: 0, category: "Sweets", imageEmoji: "🍨" },
      { id: "bd-smooth", name: "Fruit smoothie", description: "Blended fruit smoothie", priceUsd: 0, category: "Drinks", imageEmoji: "🥤" },
      { id: "bd-tea", name: "Loaded tea", description: "Take-home loaded teas", priceUsd: 0, category: "Drinks", imageEmoji: "🧋" },
    ],
  },
  {
    id: "coffee-grinder",
    name: "The Coffee Grinder",
    slug: "the-coffee-grinder",
    city: "tulsa",
    neighborhood: "Sheridan",
    cuisine: "american",
    tagline: "Coffee and pastries on South Sheridan",
    story:
      "The Coffee Grinder is a café at 5233 S Sheridan Rd, Tulsa. Fresh coffee and pastries. Confirm today’s hours at the shop before you go.",
    hours: "See the café for today’s hours",
    address: "5233 S Sheridan Rd, Tulsa, OK 74145",
    lat: 36.087,
    lng: -95.9045,
    emoji: "☕",
    accent: "#6f4e37",
    plateRating: 0,
    reviewCount: 0,
    acceptsReservations: false,
    acceptsOnlineOrders: false,
    approved: true,
    deals: [],
    menu: [
      { id: "cg-potato", name: "Build your own potato", description: "Baked potato", priceUsd: 7.99, category: "Food", imageEmoji: "🥔" },
      { id: "cg-cbr", name: "Chicken bacon ranch potato", description: "Baked potato", priceUsd: 7.99, category: "Food", imageEmoji: "🥔" },
      { id: "cg-loaded", name: "Loaded potato", description: "Baked potato", priceUsd: 7.99, category: "Food", imageEmoji: "🥔" },
      { id: "cg-muffin", name: "Muffin", description: "Bakery", priceUsd: 3.99, category: "Bakery", imageEmoji: "🧁" },
      { id: "cg-cake", name: "Coffee cake", description: "Bakery", priceUsd: 3.99, category: "Bakery", imageEmoji: "🍰" },
      { id: "cg-mousse", name: "Cold brew mousse", description: "Bakery", priceUsd: 3.14, category: "Bakery", imageEmoji: "☕" },
      { id: "cg-bread", name: "Bread slice", description: "Bakery", priceUsd: 2, category: "Bakery", imageEmoji: "🍞" },
    ],
  },
  {
    id: "andolinis",
    name: "Andolini’s Pizzeria",
    slug: "andolinis-pizzeria",
    city: "tulsa",
    neighborhood: "Cherry Street",
    cuisine: "pizza",
    tagline: "Cherry Street pies next door to Prossimo",
    story:
      "Andolini’s Pizzeria on Cherry Street is at 1552 E 15th St, Tulsa. Neighborhood pizzas and a full pie menu. Phone is listed with the restaurant.",
    hours: "Daily 11am–11pm",
    address: "1552 E 15th St, Tulsa, OK 74120",
    lat: 36.1404253,
    lng: -95.9697367,
    emoji: "🍕",
    logoUrl: "/restaurants/ando.png",
    accent: "#c1121f",
    plateRating: 0,
    reviewCount: 0,
    acceptsReservations: false,
    acceptsOnlineOrders: true,
    approved: true,
    deals: [],
    menu: [
      { id: "an-knots", name: "Garlic knots", description: "Knotted dough, garlic butter, oregano, romano", priceUsd: 9.5, category: "Apps", imageEmoji: "🧄" },
      { id: "an-cheesy", name: "Cheesy knots", description: "Garlic knots with cheese", priceUsd: 11.5, category: "Apps", imageEmoji: "🧄" },
      { id: "an-balls", name: "Appian Way meatballs", description: "Baked with fresh mozzarella", priceUsd: 15, category: "Apps", imageEmoji: "🍝" },
      { id: "an-caesar", name: "Caesar salad", description: "Romaine, croutons, parmesan", priceUsd: 14.5, category: "Salads", imageEmoji: "🥗" },
      { id: "an-garden", name: "Garden salad", description: "Choice of house dressing", priceUsd: 14.5, category: "Salads", imageEmoji: "🥗" },
      { id: "an-14", name: "14\" cheese pizza", description: "Custom or cheese", priceUsd: 18.5, category: "Pizza", imageEmoji: "🍕" },
      { id: "an-pep", name: "20\" pepperoni", description: "Large pie", priceUsd: 27.25, category: "Pizza", imageEmoji: "🍕" },
      { id: "an-saus", name: "20\" sausage", description: "Large pie", priceUsd: 27.75, category: "Pizza", imageEmoji: "🍕" },
      { id: "an-cheese", name: "20\" cheese pizza", description: "Custom or cheese", priceUsd: 32, category: "Pizza", imageEmoji: "🍕" },
      { id: "an-ath", name: "20\" Athenian", description: "Kalamata olives, feta, red onion, garlic, sausage", priceUsd: 29, category: "Pizza", imageEmoji: "🍕" },
      { id: "an-combo", name: "20\" Andolini’s combination", description: "Pepperoni, salami, mushrooms, onion, peppers, olives, beef, sausage", priceUsd: 35, category: "Pizza", imageEmoji: "🍕" },
    ],
  },
  {
    id: "casa-arepa",
    name: "El Arepaso Venezuelan Cafe",
    slug: "el-arepaso",
    city: "tulsa",
    neighborhood: "Yale",
    cuisine: "latin",
    tagline: "Venezuelan arepas, empanadas, and coffee",
    story:
      "El Arepaso Venezuelan Cafe is at 8036 S Yale Ave, Tulsa. Phone (918) 430-3136. A recent public listing shows Sunday 10am–6pm and Monday–Saturday 11am–8pm.",
    hours: "Sun 10am–6pm; Mon–Sat 11am–8pm",
    address: "8036 S Yale Ave, Tulsa, OK 74136",
    lat: 36.0470255,
    lng: -95.9236039,
    emoji: "🫓",
    logoUrl: "/restaurants/arepaso.png",
    accent: "#f4a261",
    plateRating: 0,
    reviewCount: 0,
    acceptsReservations: false,
    acceptsOnlineOrders: true,
    approved: true,
    deals: [],
    menu: [
      { id: "ca-arepa", name: "Arepa", description: "Venezuelan corn cake with a house filling", priceUsd: 0, category: "Arepas", imageEmoji: "🫓" },
      { id: "ca-reina", name: "Reina pepiada", description: "Chicken and avocado arepa", priceUsd: 0, category: "Arepas", imageEmoji: "🫓" },
      { id: "ca-emp", name: "Empanada", description: "Fried turnover", priceUsd: 0, category: "Empanadas", imageEmoji: "🥟" },
      { id: "ca-cheese", name: "Cheese pie", description: "Venezuelan cheese pastry", priceUsd: 0, category: "Pastry", imageEmoji: "🧀" },
    ],
  },
  {
    id: "mi-tierra",
    name: "Mi Tierra Cocina Mexicana",
    slug: "mi-tierra-cocina-mexicana",
    city: "tulsa",
    neighborhood: "KingsPoint Village",
    cuisine: "mexican",
    tagline: "Family-style Mexican kitchen on South Yale",
    story:
      "Mi Tierra Cocina Mexicana’s KingsPoint Village location is at 6030 S Yale Ave, Tulsa. The family also has kitchens at 9521 Riverside Parkway and in Glenpool. Tulsa World listed hours as 11am–10pm daily. Phone 539-215-6974.",
    hours: "Daily 11am–10pm",
    address: "6030 S Yale Ave, Tulsa, OK 74136",
    lat: 36.0735,
    lng: -95.9223,
    emoji: "🌮",
    logoUrl: "/restaurants/mitierra.png",
    accent: "#e85d04",
    plateRating: 0,
    reviewCount: 0,
    acceptsReservations: false,
    acceptsOnlineOrders: true,
    approved: true,
    deals: [],
    menu: [
      { id: "mt-queso", name: "Mi Tierra queso dip", description: "White queso. Add ground beef, chorizo, spinach, or beans", priceUsd: 8.95, category: "Apps", imageEmoji: "🧀" },
      { id: "mt-flautas", name: "Mini flautas", description: "Fried rolled tortillas, shredded beef or chicken", priceUsd: 8.95, category: "Apps", imageEmoji: "🌮" },
      { id: "mt-sampler", name: "Mi Tierra sampler", description: "Flautas, quesadilla, empanada, wings, and spinach queso", priceUsd: 12.95, category: "Apps", imageEmoji: "🍽️" },
      { id: "mt-fundido", name: "Pollo fundido", description: "Chicken, fundido cheese, and chorizo on a skillet", priceUsd: 11.95, category: "Apps", imageEmoji: "🍗" },
      { id: "mt-quesadilla", name: "Super quesadilla, lunch", description: "Flour tortilla, cheese, and shredded chicken, beef, or ground beef", priceUsd: 8.95, category: "Lunch", imageEmoji: "🌮" },
      { id: "mt-santa", name: "Santa Fe, lunch", description: "Chicken, flank steak, and shrimp over rice with grilled vegetables and cheese sauce", priceUsd: 10.95, category: "Lunch", imageEmoji: "🍤" },
      { id: "mt-fajita", name: "Fajitas, lunch", description: "Chicken or flank steak with rice, beans, and tortillas", priceUsd: 11, category: "Lunch", imageEmoji: "🥩" },
      { id: "mt-street", name: "Mexican street tacos (4)", description: "Steak, chicken, carnitas, or chorizo", priceUsd: 12.95, category: "Tacos", imageEmoji: "🌮" },
      { id: "mt-chipotle", name: "Enchiladas chipotle", description: "House specialty", priceUsd: 11.95, category: "Dinner", imageEmoji: "🌮" },
      { id: "mt-rancho", name: "Del Rancho", description: "Dinner plate with rice and beans", priceUsd: 18.95, category: "Dinner", imageEmoji: "🍽️" },
      { id: "mt-mahi", name: "Mexican mahi-mahi", description: "Grilled fish with vegetables", priceUsd: 19.95, category: "Seafood", imageEmoji: "🐟" },
    ],
  },
];

export const DEMO_PARTNER_PASSWORD = "demo1234";

export function tulsaPartnerAccounts(): AuthAccount[] {
  return TULSA_PARTNER_LOGINS.map(([id, slug]) => {
    const restaurant = TULSA_RESTAURANTS.find((r) => r.id === id);
    return {
      id: `partner-${id}`,
      email: `${slug}@gorditopass.local`,
      password: DEMO_PARTNER_PASSWORD,
      role: "restaurant" as const,
      name: `${restaurant?.name ?? id} Owner`,
      city: "tulsa" as const,
      isMember: false,
      planId: null,
      familySeats: 1,
      maxFamilySeats: 6,
      staffRole: "owner" as const,
      restaurantId: id,
      createdAt: "2026-09-25T00:00:00.000Z",
    };
  });
}

export const TULSA_PARTNER_LOGINS = [
  ["food-factory", "foodfactory"],
  ["alpha-grill", "alphagrill"],
  ["just-winging", "justwinginit"],
  ["prossimos", "prossimo"],
  ["tacos-x-mezcal", "tacosxmezcal"],
  ["kremee", "kremee"],
  ["boujee-delights", "boujee"],
  ["coffee-grinder", "coffeegrinder"],
  ["andolinis", "andolinis"],
  ["casa-arepa", "elarepaso"],
  ["mi-tierra", "mitierra"],
] as const;
